version: "3.7"

services:
  refractr:
    environment:
      PAPERTRAIL_URL: $PAPERTRAIL_URL
    image: refractr:${REFRACTR_VERSION}
    container_name: refractr
    build: ./refractr
    ports:
    - 80:80
