# these domains will be given a cert and rule through
# the ingress.yaml.template by being added to the domains
# output from refractr.py
default-domains:
  - prod.mozilla-redirects.xyz
  - refractr.mozilla.org

refracts:

- blog.mozilla.org/blog/2010/07/15/thanks-for-an-exciting-firefox-cup/:
  - firefoxcup.com
  - firefoxcup2010.com
 #- www.firefoxcup.com #FIXME: this is not currently implemented; should it?
  - www.firefoxcup2010.com

