# these domains will be given a cert and rule through
# the ingress.yaml.template by being added to the domains
# output from refractr.py
default-domains:
  - prod.mozilla-redirects.xyz
  - refractr.mozilla.org

refracts: []
