# these domains will be given a cert and rule through
# the ingress.yaml.template by being added to the domains
# output from refractr.py
default-domains:
  - prod.mozilla-redirects.xyz
  - prod.refractr.mozit.cloud
  - refractr.mozilla.org

refracts:

  # bug 1342698
  # NOTE: changed from http->https after verifying
- blog.mozilla.org/: mozillausa.org

  # bug 614684
- blog.mozilla.org/blog/2008/12/22/congratulations-fox-for-all-wins-impact-mozilla/:
  - impactmozilla.com
  - www.impactmozilla.com

- blog.mozilla.org/blog/2010/07/15/thanks-for-an-exciting-firefox-cup/:
  - firefoxcup.com
  - firefoxcup2010.com
 #- www.firefoxcup.com #FIXME: this is not currently implemented; should it?
  - www.firefoxcup2010.com

  # bug 617681
  # NOTE: changed from http->https after verifying
- blog.mozilla.org/operationfx/2007/12/14/declassified-information-and-the-winner-is/:
  - operationfirefox.com
  - www.operationfirefox.com

  # bug 1214568
- blog.mozilla.org/creative/: creative.mozilla.org
  status: 302

  # bug 908234
- blog.mozilla.org/webdev/: webdev.mozilla.org

  # bug 1243236
- careers.mozilla.org/:
  - jobs.mozilla.org
  - jobs.mozilla.com
  status: 302

  # bug 1627952
- community.mozilla.org/campaigns/common-voice-sprint: voice-sprint.mozilla.community

- community.mozilla.org/campaigns/help-firefox-win-on-android-support-users-in-your-language: supportsprint.mozilla.community

  # bug 1627952
- community.mozilla.org/campaigns/new-firefox/: newfirefox.mozilla.community

  # bug 1627952
- community.mozilla.org/campaigns/firefox-quantum-sprint/: firefoxsprint.mozilla.community

  # bug 572191
  # NOTE: changed from http->https after verifying
- crash-stats.mozilla.com/:
  - talkback.mozilla.org
  - talkback-public.mozilla.org
  - talkback-reports.mozilla.org

  # bug 695084
- developer.mozilla.org/: dev.mozilla.org

  # bug 811323
  # TODO: switch all HTTP sources to use HTTP and HTTPS, currently tests won't pass that way but once they are on Netlify they will
- developer.mozilla.org/demos/devderby/: devderby.mozilla.org

  # bug 1290923
- disconnect.me/trackerprotection/:
  - trackingprotection.info
  #- www.trackingprotection.info FIXME: NXDOMAIN
  status: 302

  # bug 1200302
- discourse.mozilla.org/c/add-ons/: forums.mozilla.org
  status: 307

  # bug 1274647
- discourse.mozilla-community.org/c/firefox-development/: ask.mozilla.org
  status: 307

  # bug 998526, 20170328
- docs.google.com/forms/d/1VSlo6TZ5p42LyTx2q7Wd5vQ5hZHvWtA9JN6JWicXmBM/viewform/: confsurvey.mozilla.org

  # bug 1225273, 1359534
- docs.taskcluster.net/: taskcluster.net
  status: 302

  # bug 1263033
- donate.mozilla.org/: join.mozilla.org
  status: 307

  # bug 1311146
- donate.mozilla.org/: sendto.mozilla.org
  status: 307

  # bug 1502902
  # FIXME: valid anymore, considering the redirects below?
- events.mozilla.org/techspeakers/: techspeakers.mozilla.org

  # bug 1195576
  # FIXME: this commented out redirect is incorrect, added correct one below
  #- mozillafoundation.org:
- foundation.mozilla.org/:
  - mozillafoundation.com
  - mozillafoundation.net

  # bug 1334200
- github.com/mozilla/popcorn-js/:
  - popcornjs.org
    #- www.popcornjs.org

  # bug 1462137
- hubs.mozilla.com/:
  - hub.mozilla.com
  - hub.mozilla.org

  # bug 613649
- krakenbenchmark.mozilla.org/: krakenbenchmark.mozilla.com

  # bug 784556, 880423
- mana.mozilla.org/wiki/display/SD/print.mozilla.com/: print.mozilla.com

  # bug 1421587
- medium.com/mozilla-open-innovation/: open.mozilla.org
  status: 302

  # bug 1396954
  # FIXME: this commented out redirect is incorrect, added correct one below
  #- research.mozilla.org/mixed-reality: mixedreality.mozilla.org
- mixedreality.mozilla.org/: mixedreality.mozilla.org

  # bug 1330438
- moz-releng-docs.readthedocs.io/en/latest/: docs.pub.build.mozilla.org

  # bug 1335596
  # NOTE: changed redirect to its final destination
- mozilla.design/: designlanguage.mozilla.org

  # bug 855746
  # TODO: figure out why this won't pass tests.  It works for me in curl
- mozilla.ec/:
  - mozillaecuador.org
  #- www.mozillaecuador.org FIXME: NXDOMAIN

  # bug 1533035
- mozilla.github.io/geckoview/:
  - gv.dev
  - geckoview.dev
  status: 302

- mozilla.github.io/oi-website/: openinnovation.mozilla.org

  # bug 1463086
- mozilla.org/nl/:
  - mozilla.nl
  - www.mozilla.nl

  # bug 1538932
- mozilla.report/: reports.telemetry.mozilla.org

  # bug 681943
- mozillafestival.org/: festival.mozilla.org
  status: 302

  # bug 1441865
- mozilla-releng.net/treestatus/: treestatus.mozilla.org
  status: 302

  # bug 1293353
- mozilla.service-now.com/: thehub.mozilla.com
  status: 302

  # bug 1596457
- mozilla-spidermonkey.github.io/: spidermonkey.dev

  # bug 1459170
- perf-html.io/: cleopatra.io
  status: 302

- pontoon.mozilla.org/:
    # bug 985510
  - pontoon.mozillalabs.com
    # bug 1666547
  - l10n.mozilla.org

  # bug 1315316
- qsurvey.mozilla.com/s3/FirefoxInput/:
  - m.input.mozilla.org
  - m.input.mozilla.com
  - feedback.mozilla.org
  status: 302

  # bug 1522224
- testpilot.firefox.com/: contribute.testpilot.firefox.com

  # bug 1614193
- voice.mozilla.org/fy-NL/: voice.mozilla.frl
  status: 302

  # bug 1419948
  # TODO: verify this works as before
- web.archive.org/web/20180106223649/https://webfwd.org/:
  - webfwd.org
  #- www.webfwd.org FIXME: gives SSL Cert Error
  - webfwd.net
  - www.webfwd.net
  status: 307

  # bug 510914
  # NOTE: changed from http->https after verifying
- m.wiki.mozilla.org/Main_Page/: library.mozilla.org

  # bug 1035550
- wiki.mozilla.org/: wiki.mozilla.com

  # bug 1203755
- wiki.mozilla.org/B2G/:
  - boot2gecko.org
  #- www.boot2gecko.org FIXME: NXDOMAIN
  status: 307

  # bug 1290260
- wiki.mozilla.org/DeveloperServices/HistoricalVCS/: git.mozilla.org
  status: 302

  # bug 1492531
- wiki.mozilla.org/Pastebin/: pastebin.mozilla.org

  # bug 804895
- wiki.mozilla.org/Platform/AreWeFunYet/:
  - arewefunyet.com
  #- www.arewefunyet.com FIXME: NXDOMAIN

  # bug 722504
- wiki.mozilla.org/Security/Events/CTF/:
  - mozillactf.org
  #- www.mozillactf.org FIXME: NXDOMAIN
  status: 302

  # bug 1185027
- www.contributejson.org/: contributejson.org
  status: 302

  # bug 1384357
- www.extensiontest.com/: extensiontest.com
  status: 302

  # bug 1136318
  # NOTE: changed from http->https after verifying
- www.mozilla.de/:
  - mozilla.at
  #- www.mozilla.at FIXME: NXDOMAIN

- www.mozilla.org/: mozilla-podcasts.org

  # FIXME: redirect below didnt work; replaced with what is on prod
  #- marketplace.firefox.com/: apps.mozillalabs.com
- www.mozilla.org/: apps.mozillalabs.com

  # bug 1361114
- www.mozilla.org/: webwewant.mozilla.org

  # bug 1169224, 1473015
- www.mozilla.org/:
  - mozilla.org.uk
  - www.mozilla.org.uk
  status: 302

  # bug 1461516
- www.mozilla.org/: smartdogz.org
  status: 302

  # FIXME: does this really have to be 307 different from 302 above?
- www.mozilla.org/: www.smartdogz.org
  status: 307

- www.mozilla.org/: triagebot.mozilla.org

  # bug 537925
  # NOTE: simplified this after testing, this simple redirect is all that is needed
- www.mozilla.org/contribute/: contribute.mozilla.org

  # bug 1255221
- www.mozilla.org/contribute/friends/: friends.mozilla.org
  status: 302

  # bug 1274647
- discourse.mozilla-community.org/c/firefox-development/: ask.mozilla.org
  status: 307

  # bug 1212612, 1212612
  # FIXME: this commented out redirect is incorrect, added correct one below
  #- www.mozilla.org/firefox/new/?utm_source=getfirefox-de&utm_medium=referral:
- www.mozilla.org/de/firefox/new/:
  - getfirefox.de
  #- www.getfirefox.de FIXME: NXDOMAIN
  - firefox-hacks.de
  - www.firefox-hacks.de
  - firefox2.de
  - www.firefox2.de

  # bug 896570
- www.mozilla.org/firefox/?redirect_source=getfirefox-com:
  - mozillafirefox.com
  - www.mozillafirefox.com
  - firefoxbrowser.com
  - www.firefoxbrowser.com
  - firefoxbrowser.org
  - www.firefoxbrowser.org

  # bug 1415362
- www.mozilla.org/firefox/?utm_medium=referral&utm_source=firefoxquantum-com: firefoxquantum.com

  # bug 1492428
- www.mozilla.org/fr/firefox/new/?utm_source=mozilla-fr&utm_medium=referral:
  - mozilla.fr
  - www.mozilla.fr

  # bug 1212631, 1427843
  # FIXME: this commented out redirect is incorrect, added correct one below
  #- www.mozilla.org/firefox/new/?utm_source=getfirefox-co-uk&utm_medium=referral: getfirefox.co.uk
- www.mozilla.org/en-GB/firefox/new/: getfirefox.co.uk

  # bug 1492428
- www.mozilla.org/en-GB/firefox/new/?utm_source=mozilla-eu&utm_medium=referral:
  - mozilla.eu
  - www.mozilla.eu
  - mozila.eu
  - www.mozila.eu

  # bug 1025191
- www.mozilla.org/en-US/:
  - mozilla.ca
  #- www.mozilla.ca FIXME: NXDOMAIN

  # bug 941881
  # NOTE: changed from http->https after verifying
- www.mozilla.org/en-US/contribute/studentambassadors/:
  - ambassadors.mozilla.org
  - students.mozilla.org
  - fsa.mozilla.org

  # bug 1335617
- www.mozilla.org/en-US/about/policy/lean-data/:
  - leandatapractices.org
  - www.leandatapractices.org
  - leandatapractices.com
  - www.leandatapractices.com
  status: 302

  # bug 1056359
- www.mozilla.org/en-US/firefox/new/:
  - mozilla.it
  #- wwww.mozilla.it FIXME: NXDOMAIN

- www.mozilla.org/firefox/:
  # bug 838939
  - downloadmozillafirefox.com
  # bug 948963
  - spark.mozilla.org
  status: 302

  # bug 1351245
- 'www.mozilla.org/firefox/channel/desktop/#developer': aurora.mozilla.org
  status: 302

  # bug 656457
- 'www.mozilla.org/firefox/channel/#beta': beta.mozilla.org

  # bug 1301642, 1326390
- 'www.mozilla.org/firefox/channel/#nightly': nightly.mozilla.org
  status: 302

  # bug 1212612, 1427843
- www.mozilla.org/firefox/new/?utm_source=getfirefox-net&utm_medium=referral:
  - getfirefox.net
  #- www.getfirefox.net FIXME: NXDOMAIN

  # bug 688019, 1427843
- www.mozilla.org/firefox/new/?utm_source=getfirefox-org&utm_medium=referral:
  - getfirefox.org
  - www.getfirefox.org

  # bug 1262196, 1427843
- www.mozilla.org/firefox/new/?utm_source=firefox-hu&utm_medium=referral:
  - firefox.hu
  - www.firefox.hu

  # bug 749836
- www.mozilla.org/firefox/new/?utm_source=firefox-pt&utm_medium=referral:
  - firefox.pt
  - www.firefox.pt

  # bug 1243355
- www.mozilla.org/fy-NL/:
  - mozilla.frl
  #- www.mozilla.frl FIXME: NXDOMAIN
  status: 302

  # bug 1268570, 1427843
  # FIXME: this commented out redirect is incorrect, added correct one below
  #- www.mozilla.org/firefox/new/?utm_source=firefox-lt&utm_medium=referral:
- www.mozilla.org/lt/firefox/:
  - firefox.lt
  #- www.firefox.lt FIXME: NXDOMAIN

- www.mozilla.org/MPL/: mpl.mozilla.org

  # bug 1311392
- www.mozilla.org/pl/firefox/new/:
  - mozillafirefox.pl
  - www.mozillafirefox.pl
  status: 302

  # bug 1440375
- www.mozilla.org/pt-BR/: mozilla.com.br

  # bug 971390
- www.mozilla.org/ru/firefox/new/:
  - firefoxik.ru
  #- www.firefoxik.ru FIXME: NXDOMAIN

  # bug 1427843
- www.mozilla.org/firefox/new/?utm_source=firefox-be&utm_medium=referral:
  - firefox.be
  - www.firefox.be

  # bug 692904
  # FIXME: apache points to http; this will go to https
- www.mozilla-russia.org/:
  - mozilla.com.ru
  - www.mozilla.com.ru

  # bug 1255190
- www.openwebgames.com/: openwebgames.com
  status: 302

  # NOTE: changed from http->https after verifying
  #- www.thunderbird.net/:
- www.thunderbird.net/calendar/:
  - lightning-project.org
  #- www.lightning-project.org FIXME: NXDOMAIN
