$schema: http://json-schema.org/draft-08/schema
title: refractr
type: object
required:
- refracts
additionalProperties: false
properties:
  refracts:
    $id: '#/properties/refracts'
    default: []
    title: refracts
    type: array
    items:
      oneOf:
      - $ref: '#/defs/simple-refract'
      - $ref: '#/defs/complex-refract'
defs:
  if-predicate:
    default: ''
    title: if-predicate
    type: string
    pattern: '^(^|$).*$'
  test-url:
    default: ''
    title: test-url
    type: string
    pattern: '^(https?:\/\/)([A-z0-9]+([A-z0-9\.\-]+)\/)([A-z0-9\-_]+\/)*([A-z0-9$\/\.\-_:]+)?(\?[A-z0-9\.\-:=]+(&[A-z0-9\.\-:=]+)*)?(#[A-z0-9\-_]+)?$'
  test-urls:
    default: []
    title: test-urls
    type: array
    items:
      $ref: '#/defs/test-url'
  src-url:
    default: ''
    title: src-url
    type: string
    pattern: '^(?!https?:\/\/)((\*|[A-Za-z0-9]+)([\.\-][A-Za-z0-9]+)+)$'
  src-urls:
    default: []
    title: src-urls
    type: array
    items:
      $ref: '#/defs/src-url'
  dst-url:
    default: ''
    title: dst-url
    type: string
    # single '$' added to file matcher to allow nginx exprs: $lang $request_uri
    pattern: '^(?!https?:\/\/)([A-z0-9]+([A-z0-9\.\-]+)\/)([A-z0-9\-_]+\/)*([A-z0-9$\/\.\-_:]+)?(\?[A-z0-9$\.\-:=]+(&[A-z0-9$\.\-:=]+)*)?(#[A-z0-9\-_]+)?\??$' # added optional '?' for nginx rewrite
  nginx-url:
    default: ''
    title: nginx-url
    type: string
    pattern: '$host$request_uri'
  dst-redirect:
    default: {}
    title: dst-redirect
    type: object
    minProperties: 1
    additionalProperties: false
    patternProperties:
      '^\/([A-z0-9\-_]+\/)*([A-z0-9\/\*\.\-_:]+)?$':
        $ref: '#/defs/dst-url'
  dst-rewrite:
    default: {}
    title: dst-rewrite
    type: object
    minProperties: 1
    additionalProperties: false
    properties:
      if:
        $ref: '#/defs/if-predicate'
      # FIXME: this ugly, pls fix
      redirect:
        default: ''
        title: redirect-val
        type: string
        pattern: '(.*)'
    patternProperties:
      '^\^.*$':
        $ref: '#/defs/dst-url'
  dsts:
    type: array
    items:
      oneOf:
      - $ref: '#/defs/dst-redirect'
      - $ref: '#/defs/dst-rewrite'
  test:
    default: {}
    title: test
    type: object
    minProperties: 1
    maxProperties: 1
    additionalProperties: false
    patternProperties:
      '^(https?:\/\/)([A-z0-9]+([A-z0-9\.\-]+)\/)([A-z0-9\-_]+\/)*([A-z0-9$\/\.\-_:]+)?(\?[A-z0-9$\.\-:=]+(&[A-z0-9$\.\-:=]+)*)?(#[A-z0-9\-_]+)?$':
        $ref: '#/defs/test-url'
  tests:
    default: []
    title: tests
    type: array
    items:
      $ref: '#/defs/test'
  simple-refract:
    default: {}
    title: simple-refract
    type: object
    minProperties: 1
    maxProperties: 2
    additionalProperties: false
    properties:
      status:
        type: integer
    patternProperties:
      # same as #/defs/dst-url
      '^(?!https?:\/\/)([A-z0-9]+([A-z0-9\.\-]+)\/)([A-z0-9\-_]+\/)*([A-z0-9$\/\.\-_:]+)?(\?[A-z0-9$\.\-:=]+(&[A-z0-9$\.\-:=]+)*)?(#[A-z0-9\-_]+)?$':
        oneOf:
        - $ref: '#/defs/src-url'
        - $ref: '#/defs/src-urls'
  complex-refract:
    default: {}
    title: complex-refract
    type: object
    minProperties: 2
    maxProperties: 4
    required:
    - srcs
    - dst
    additionalProperties: false
    properties:
      srcs:
        oneOf:
        - $ref: '#/defs/src-url'
        - $ref: '#/defs/src-urls'
      dst:
        $ref: '#/defs/dsts'
      status:
        type: integer
      tests:
        $ref: '#/defs/tests'
