name: Publish Refractr
on:
  push:
    branches:
      - main
      - replace-aws-user-to-role # double check after changes in AWS
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  publish:
    runs-on: ubuntu-latest
   permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::783633885093:role/ecr-refractr-iam
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Publish
        run: doit publish
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

      - name: Show details
        run: doit show
